### ISSUE TITLE
Incentivize Teams to submit flags ASAP

### ISSUE THREAD

**Issue by pereztr5** [pereztr5/cyboard#20]
This can be time based on the first challenge submitted.
The reason for this is because teams will sit on flags and wait until the very end.

**Comment by tbutts** [comment]
After discussing this more with the CNY Hackathon organizers, we will be deprioritizing this issue.

#### Highlights from the conversation:
> **Butters:** The easiest way to design this, would be a flat percentage of bonus points for 1st to submit, 2nd, etc. Like 40% extra, then 20% extra, and everyone else would get the base reward. The numbers would be configurable.

> **Organizer 1:** [...] If we in some way devalue the CTF points over time I'm worried how that might impact the other areas of the competition.  Will teams go for CTF first at the expense of other aspects?

> **Organizer 2:** Perhaps the score screen can be broken out to differentiate the scores.
 [...] which could allow red ream to focus on teams with higher infrastructure scores and not total score which would eliminate the value of flag hoarding.

I followed through with the suggestion, adding #27. We'll see how the competition goes, and reevaluate afterwards. For now, the issue is closed, with potential to be reopened.
